"""
Django settings for fileupload project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t%sa%emmb966roefevildepm&xmdig9kyx0+y5%+_yr$(scs$%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'upload',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fileupload.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fileupload.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


PUBLIC_KEY = """
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4v2Jg2Hk6tfgr4oKVoO9
grxCTHAXcBJeLR0QzDS0f7yseTg2YTtxVnxO9fFEf54/ZBvHD0Wjtbwx7S452oPm
xAHYcKOTfFrer72qGgdgCeSDFQTRXtRPsVH1UNukkV9rFMYtVfnYwLi0AE1llIEF
L5k2buKqrHCAAKwO989G0WBcUyJz8uqzclcPf+DQpxjez9Ua+jb7FVR9XQBCgOdu
O2fhhEoq/e4f5fwleRVfCL8qeyji0CLqqwlaLaS7JpGdk+YpGChHgX0acUzk6rGM
LsOzsaRmBEWadlg2MbYG1PYo8WYLHNTPSSf5GTAZkdN+8PG01EK8FcMJZZWgRj8n
VQIDAQAB
"""

PRIVATE_KEY ="""
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDi/YmDYeTq1+Cv
igpWg72CvEJMcBdwEl4tHRDMNLR/vKx5ODZhO3FWfE718UR/nj9kG8cPRaO1vDHt
Ljnag+bEAdhwo5N8Wt6vvaoaB2AJ5IMVBNFe1E+xUfVQ26SRX2sUxi1V+djAuLQA
TWWUgQUvmTZu4qqscIAArA73z0bRYFxTInPy6rNyVw9/4NCnGN7P1Rr6NvsVVH1d
AEKA5247Z+GESir97h/l/CV5FV8Ivyp7KOLQIuqrCVotpLsmkZ2T5ikYKEeBfRpx
TOTqsYwuw7OxpGYERZp2WDYxtgbU9ijxZgsc1M9JJ/kZMBmR037w8bTUQrwVwwll
laBGPydVAgMBAAECggEADCNTpadn9tjpZmmiyOKNkT6g6vZ5gmAxEgeCXPEaj9QW
gvrrCYMEugO2szceGxbqu98yY1ItgWvZXZ4BsPoprmSM3uUYX2d6jfo97NtlGtJR
4h9aVNBUnJ5N2G+OWsm376nzRawxF4ko8vUwj+LgVJ3ER+SuDL+NULvipwS5/Dsp
mtqxnZ8dQr4Giy80+na+2dHuq6WhC7gP+WMjNPjdnWYydTycfewkNBAQ8BeM9Gpl
TKHD42VizO8YGVsZkPYkMs7ffnw595rHe2preYvphFcugERVr38VGC7O2V9dO5uj
fyoMOUGQYz8FPliSudofQ+qwnRaY+N0RRZXaHNwVYQKBgQDrT/sUKKXoek4oGfH2
pL/qrz2zhvQqsjMVhxJCe6madTMJCBgvhBF86Ye10AYeG3u61LzCuWkX5/03X+n2
wrgx/A6pI5cb71nr9JV5+NGmdlwGS3SWULvDzBoH0poCJF4MnlH++XuImjsGcx6d
ABEf2GSe/dBJaDFSi7CM1n+wZQKBgQD28kH3V/eEAydhhUoKkwEpjs00kNxGl2z1
62Xd01gCSX02B3U+YuotlONlwC4vuevC/zVpBDAcl0x9WfgPluU0vLCURfbI5OJF
cmMglV3K5JXIZP5S+4uMbYvdyQ0lKX/jJEAtWmgYM5bS6y+dMPGpfk/CLSQGiCpN
uPosL0SUMQKBgQCBGAXUz2AFpGOQWHuIJmYraCxfe2AktFKWMt3vn0wysq1m/QvX
tYqqjqunMRLKHaXJn8BWy8U+GkWuxW3jtHu84F1iqWXTK4KXkj0XB0xtGG3v/iFd
/bik+ContIBNQIpgPdMaIOCG1qYfKbTXyRub7ul02CYWv5Sfhoc7HMo8iQKBgDL3
cPHxr94JIJmZ/twL1xOSq3uL4kqXeh+PQ+jyc5mVPUhnZaVImPhrYDth3KZxAt2t
+oIAIUXlXB4K8Y2WIRwvTWpsvjBcPO8EWr0g1sjHQLqpTWwnCngjK9jMY/AljoV8
t9okbJOCIkDJ1Xvl3BqVPTTgSC0o8UI1STzRTKAhAoGBANd2c8wwkj8BUOKE6COE
HH1t21g+pnvIjswBazjS4fYU74l2shKpZ5/n4BkXpKDKPsdlchgd6XyTkt732h+0
Hp4fYVnEw2rZG1JBfcpCLeVdWHAraBKOyuuKuK8AQU96pkf1epPcs3j433KolGhy
V55l8Y34tb66RMMhENJXrwSH
-----END PRIVATE KEY-----
"""